kksng/korus-ui

CHANGELOG.md
leda/src/Calendar/helpers.ts

Revert "Feature/fend 1021"

---

CHANGELOG.md
leda/form/helpers.ts

Changed "value.acceptedFiles.length !== 0"

FEND-975 DropZone isRequired fixed

---

CHANGELOG.md
demo/components/CheckBox.tsx
demo/cypress/CheckBox/index.tsx
leda/components/CheckBox/CheckBox.test.tsx
leda/components/CheckBox/__snapshots__/CheckBox.test.tsx.snap
leda/components/CheckBox/index.tsx
leda/src/Calendar/helpers.ts
styles/themes/light/components/CheckBox/_checkbox.scss

Now component CheckBox accepts unnecessary attribute isSemi
The attribute replaces className _semi
Pls check my solution. Did I get the problem right?

FEND-973 CheckBox isSemi

---

CHANGELOG.md
leda/components/AutoComplete/AutoComplete.test.tsx
leda/components/AutoComplete/handlers.ts
leda/components/AutoComplete/types.ts
leda/components/DropDownSelect/DropDownSelect.test.tsx
leda/components/DropDownSelect/handlers.ts
leda/components/DropDownSelect/types.ts
leda/components/MultiSelect/MultiSelect.test.tsx
leda/components/MultiSelect/handlers.ts
leda/components/MultiSelect/types.ts
leda/components/NumericRange/NumericRange.test.tsx
leda/components/NumericRange/index.tsx
leda/components/NumericRange/types.ts
leda/components/NumericTextBox/NumericTextBox.test.tsx

Добавлен обработчик нажатия на enter "onEnterPress"
компонентам:
AutoComplete, DropDownSelect, MultiSelect, DateRange, NumericRange, NumericTextBox
В остальных компонентах формы обработчик уже есть

FEND-1032 [Form Components] Добавить атрибут onEnterPress всем компонентам формы

---

CHANGELOG.md
leda/components/DropDownSelect/handlers.ts

Исправлено некорректное поведение компонента с пустым значением при нажатии на Enter

FEND-1043 DropDownSelect with empty data on "enter" press bug fixed

---

CHANGELOG.md
leda/form/helpers.ts

Fixed value check on form validation helper.

FEND-1041 [FileDrop] Bug fixed with isRequired validation after uploading incorrectly file

---

CHANGELOG.md
leda/components/AutoComplete/index.tsx
leda/components/DropDownSelect/index.tsx
leda/components/MultiSelect/index.tsx
leda/components/NumericTextBox/helpers.ts

AutoComplete
DropDownSelect
MultiSelect
NumericTextBox
NumericRange

FEND-1048 Fixed warning message of onEnterPress event

---

CHANGELOG.md
leda/components/AutoComplete/handlers.ts
leda/components/AutoComplete/helpers.ts
leda/components/AutoComplete/index.tsx
leda/components/DropDownSelect/index.tsx
leda/components/MultiSelect/index.tsx
leda/components/NumericRange/handlers.ts
leda/components/NumericRange/types.ts
leda/components/NumericTextBox/helpers.ts
leda/form/helpers.ts
leda/src/DateTimeInput/hooks.ts

В файле /helpers 
Есть функция correсt
Которая раньше вызывалась из обработчика onBlur и возвращала ранее выбранное пользователем значение если установлен флаг shouldCorrectValue
Сейчас я вызов этой функции добавил в методы onEnterPress и onClickSuggestion
Но что бы я не писал в описании типа event в функции correct, все время какие-то коллизии. То тут, то там. 
Сейчас написано   event: any, 
Других я способов не нашёл :-)

Feature/fend FEND-913 [AutoComplete] fix shouldCorrectValue uncontrolled mode

---

CHANGELOG.md
leda/src/MaskedInputBase/handlers.ts

Changed the new char position source

FEND-999 [MaskedInput] Fixed bug with incorrectly cursor position when typing same chars

---

CHANGELOG.md
leda/components/Password/index.tsx
leda/components/Password/types.ts

Password. Added showValidation prop to hide validation messages

FEND-1031 [Password] showValidation prop

---

CHANGELOG.md
leda/components/Textarea/handlers.ts
leda/components/Textarea/index.tsx
leda/components/Textarea/types.ts

Textarea. shouldAutoResize prop - automatically adjust vertical height when required.

FEND-1047 [Textarea] shouldAutoResize prop

---

CHANGELOG.md
leda/components/DateTimePicker/types.ts
leda/components/TimePicker/types.ts
leda/components/TimeRange/types.ts
leda/src/Calendar/helpers.ts
leda/src/DateTimeInput/DateTimeInput.tsx
leda/src/DateTimeInput/constants.ts
leda/src/DateTimeInput/handlers/handleBlur.ts
leda/src/DateTimeInput/handlers/handleKeyDown.ts
leda/src/DateTimeInput/helpers.ts
leda/src/DateTimeInput/types.ts

Added supporting of timeMin timeMax props and time limiting in DateTimeInput component.
Added TimeLimits type.
Handed out the applyTimeLimits helper.

FEND-1003 [TimePicker][DateTimePicker] Time limits timeMin and timeMax not works

---

CHANGELOG.md
leda/components/AutoComplete/index.tsx
leda/components/Input/index.tsx
leda/components/MultiSelect/MultiSelect.test.tsx
leda/components/MultiSelect/index.tsx
leda/components/Password/index.tsx

FEND-1058 [Autocomplete][Input][MultiSelect][Password] fix hide clear button when disabled

FEND-1058 [Autocomplete][Input][MultiSelect][Password] fix hide clear button when disabled

---

CHANGELOG.md
demo/components/DatePicker/DisabledDates.tsx
demo/components/DatePicker/index.tsx
demo/components/DateTimePicker.tsx
leda/components/DatePicker/types.ts
leda/components/DateRange/types.ts
leda/components/DateTimePicker/types.ts
leda/components/DateTimeRange/types.ts
leda/src/Calendar/Calendar.tsx
leda/src/Calendar/DateCell.tsx
leda/src/Calendar/DateView.tsx
leda/src/Calendar/helpers.test.ts
leda/src/Calendar/helpers.ts
leda/src/Calendar/types.ts
leda/src/DateTimeInput/DateTimeInput.tsx
leda/src/DateTimeInput/handlers/handleChange.ts
leda/src/DateTimeInput/types.ts
leda/src/DateTimeInputRange/index.tsx
leda/src/DateTimeInputRange/types.ts

Added disabledDates prop. Array of dates and dates ranges that are disabled to be selected as a value.

FEND-717 [DateTimePicker] add disabledDates prop

---

CHANGELOG.md
demo/components/DatePicker/DisabledDates.tsx
demo/components/DatePicker/index.tsx
demo/components/DateTimePicker.tsx
leda/components/AutoComplete/index.tsx
leda/components/DatePicker/types.ts
leda/components/DateRange/types.ts
leda/components/DateTimePicker/types.ts
leda/components/DateTimeRange/types.ts
leda/components/Input/index.tsx
leda/components/MultiSelect/MultiSelect.test.tsx
leda/components/MultiSelect/index.tsx
leda/components/NumericRange/helpers.test.ts
leda/components/NumericRange/helpers.ts
leda/components/Password/index.tsx
leda/src/Calendar/Calendar.tsx
leda/src/Calendar/DateCell.tsx
leda/src/Calendar/DateView.tsx
leda/src/Calendar/helpers.test.ts
leda/src/Calendar/helpers.ts
leda/src/Calendar/types.ts
leda/src/DateTimeInput/DateTimeInput.tsx
leda/src/DateTimeInput/handlers/handleChange.ts
leda/src/DateTimeInput/types.ts
leda/src/DateTimeInputRange/index.tsx
leda/src/DateTimeInputRange/types.ts
package-lock.json
package.json

Release 0.29.0

---

CHANGELOG.md
package-lock.json
package.json

Update version to 0.30.0

---

cypress/integration/Input/index.spec.js
demo/cypress/Input/index.tsx

FEND-1051 [Input] tests focus input on clear button click

---

package-lock.json
package.json

0.31.0-beta

---

CHANGELOG.md
cypress/integration/DatePicker/index.spec.js
cypress/integration/TimePicker/index.spec.js
demo/CypressLayout.tsx
demo/cypress/DatePicker/index.tsx
demo/cypress/TimePicker/index.tsx
demo/cypress/index.ts
leda/components/Validation/helpers.ts

Validators didn't work because date values were not checked correctly

FEND-1131 [DatePicker][TimePicker] Fixed validation

---

cypress/integration/Collapse/index.spec.js
debug.log
demo/CypressLayout.tsx
demo/cypress/Collapse/index.tsx
demo/cypress/index.ts

Cypress test for the Collapse component with an example of the component.

FEND-1208 [Test for the Collapse]

---

demo/components/Button/Basic.tsx
demo/components/Button/Minimal.tsx
demo/components/Button/index.tsx
demo/components/ButtonGroup/Minimal.tsx
demo/components/ButtonGroup/index.tsx

Обязательных props у этого компонента нет.

FEND-1153 [ButtonGroup] Added minimal demo example

---

demo/components/A/Basic.tsx
demo/components/A/Minimal.tsx
demo/components/A/index.tsx

Обязательных props у этого компонента нет.

FEND-1153 [A] Added minimal demo example

---

storybook/storybook/stories/form/Checkbox/Examples/Semi.js
storybook/storybook/stories/form/Checkbox/propsDescription.js

FEND-1303 [CheckBox] 

---

CHANGELOG.md
korus-ui/src/MaskedInputBase/constants.ts
korus-ui/src/MaskedInputBase/handlers.ts
korus-ui/src/MaskedInputBase/helpers.test.tsx
korus-ui/src/MaskedInputBase/helpers.ts
package-lock.json
package.json

* FEND-1521 [MaskedInput] Fixed autocomplete
* Added compareText helper tests

Release v.0.45.1
